name: Universum check
on: push

jobs:
  universum_check:
    name: Universum check
    runs-on: ubuntu-latest

    steps:
    - name: Setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependency
      run: pip install universum[test]

    - name: Test script
    - uses: actions/github-script@v5
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })

    - name: Create issue using REST API
      run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail

    - name: Universum
      run:
        python -u -m universum
        --fail-unsuccessful
        --vcs-type=git
        --git-repo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        --git-refspec $GITHUB_REF_NAME
        --no-archive
        --no-diff

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: artifacts/*.xml

    - name: Collect artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: artifacts
        path: artifacts
