name: Universum check
on: push
permissions:
  issues: write
  discussions: write
  pull-requests: write

jobs:
  universum_check:
    name: Universum check
    runs-on: ubuntu-latest

    steps:
    - name: Setup python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependency
      run: pip install universum[test]
      

    - name: Create comment using REST API
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/k-dovgan/Universum/issues/21/comments \
          -d '{"body":"Me too"}'

    - name: File
      run:
        cat ${{ github.env.GITHUB_EVENT_PATH }}

    - name: Universum
      run:
        python -u -m universum
        --fail-unsuccessful
        --vcs-type=ghactions
        --ghactions-payload=file
        --no-archive
        --no-diff

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: artifacts/*.xml

    - name: Collect artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: artifacts
        path: artifacts

  info:
    name: print payload
    runs-on: ubuntu-latest
    steps:
    - name: Payload
      uses: hmarr/debug-action@v2
