name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment-pr:
    name: Make comment to a chat
    runs-on: ubuntu-latest

    steps:
    - name: Comment new PR
      if: github.event.pull_request && ( github.event.action == 'open' )
      run: echo New PR $NUMBER
      env:
        NUMBER: ${{ github.event.pull_request.number }}

    - name: Comment update PR
      if:  github.event.pull_request && ( github.event.action == 'syncronize' )
      run: echo Update PR $NUMBER
      env:
        NUMBER: ${{ github.event.pull_request.number }}
    

    - name: Comment new comment
      if: github.event.issue_comment && github.event.issue.pull_request
      run: echo A comment on PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}

    - name: Payload
      uses: Dovyski/payload-info-action@master
