name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment:
    name: Notify
    runs-on: ubuntu-latest

    steps:
    - name: Comment new PR
      if: github.event.pull_request && github.event.action == 'opened'
      run: echo New PR $NUMBER
      env:
        NUMBER: ${{ github.event.pull_request.number }}

    - name: Comment update PR
      if: github.event.pull_request && github.event.action == 'synchronize'
      run: echo Update PR $NUMBER
      env:
        NUMBER: ${{ github.event.pull_request.number }}
        
  report-comment:
    name: Notify about comment
    if: github.event.issue_comment
    runs-on: ubuntu-latest

    steps:
    - name: Comment new comment
      if: github.event.issue
      run: echo A comment on PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}

  info:
    name: print payload
    runs-on: ubuntu-latest
    steps:
    - name: Payload
      uses: Dovyski/payload-info-action@master
