name: Telegram bot
on:
  pull_request:
    types: [opened, synchronize, closed]
  issue_comment:
    types: created
  check_run:
    types: completed
    
jobs:
  make-comment:
    name: Send comment to TG
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_NAME: ${{ github.event.pull_request.title }}
      PR_BASE: ${{ github.event.pull_request.base.ref }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_MERGED: ${{ github.event.pull_request.merged_by.login }}
      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
      COMMENT_URL: ${{ github.event.comment.html_url }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMENT_NUMBER: ${{ github.event.issue.number }}
      NL: /n

    steps:
    - name: Comment new PR
      if: github.event.pull_request && github.event.action == 'opened'
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.PR_AUTHOR }} created new PR#${{ env.PR_NUMBER }} '${{ env.PR_NAME }}' to branch '${{ env.PR_BASE }}'.
          See here: ${{ env.PR_URL }}

    - name: Comment update PR
      if: github.event.pull_request && github.event.action == 'synchronize'
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.PR_AUTHOR }} updated PR#${{ env.PR_NUMBER }};
          ${{ env.NL }} see here: ${{ env.PR_URL }}

    - name: Comment merge PR
      if: github.event.pull_request && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.PR_MERGED }} merged PR#${{env.PR_NUMBER }} to branch ${{ env.PR_BASE }}

    - name: Comment new comment
      if: github.event.comment
      run: echo TEXT=$TEXT >> $GITHUB_ENV
      env:
        TEXT: |
          ${{ env.COMMENT_AUTHOR }} posted the following comment to issue #${{ env.COMMENT_NUMBER }}:
          ${{ env.COMMENT_BODY }}



    - name: Send comment to TG
      if: env.TEXT
      run: curl --get --data-urlencode "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" --data-urlencode "text=${{ env.TEXT }}" $URL
      env:
        URL: https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

  info:
    name: print payload
    runs-on: ubuntu-latest
    steps:
    - name: Payload
      uses: hmarr/debug-action@v2
