name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment-pr:
    name: Make comment to a chat
    runs-on: ubuntu-latest

    steps:
    - name: Comment new PR
      if:  github.event.pull_request
      run: |
        echo $ACTION
        if ($ACTION == "open")
          echo This is new PR $NUMBER
        elif ($ACTION == "synchronize")
          echo This is update for PR $NUMBER
        fi
      env:
        ACTION: ${{ github.event.action }}
        NUMBER: ${{ github.event.pull_request.number }}

    - name: Comment new comment
      if: github.event.issue_comment && github.event.issue.pull_request
      run: echo A comment on PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}

    - name: Payload
      uses: Dovyski/payload-info-action@master
