name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment-pr:
    name: Make comment to a chat
    runs-on: ubuntu-latest

    steps:
    - name: Payload
      uses: Dovyski/payload-info-action@master
    
    - name: Comment new PR
      if: github.event.pull_request
      run: echo A PR is $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}
        
    - name: Comment PR update
      if: github.event.pull_request && github.event.action.synchronize
      run: echo This is PR update $NUMBER
      env:
        NUMBER: ${{ github.event.pull_request.number }}

    - name: Comment new comment
      if: github.event.issue_comment && github.event.issue.pull_request
      run: echo A comment on PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}
