name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment:
    name: Notify about PR
    runs-on: ubuntu-latest

    steps:
    - name: Comment new PR
      if: github.event.pull_request && github.event.action == 'opened'
      run: curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$TEXT"
      env:
        AUTHOR: ${{ github.event.pull_request.user.login }}
        NAME: ${{ github.event.pull_request.title }}
        BASE: ${{ github.event.pull_request.base.ref }}
        URL: ${{ github.event.pull_request.html_url }}
        TEXT: "$AUTHOR created new PR '$NAME' to branch '$BASE'; see here:\n$URL"

    - name: Comment update PR
      if: github.event.pull_request && github.event.action == 'synchronize'
      run: curl $LINK
      env:
        NUMBER: ${{ github.event.pull_request.number }}
        LINK: "https://api.telegram.org/bot2006604930:AAG5XkarlytozMG6YGnVkDkB2tNTm5H2BuM/sendMessage?chat_id=-1001783686076&text='This is text'"
        TEXT: "Update the PR $NUMBER"
        
  report-comment:
    name: Notify about comment
    if: github.event.comment && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
    - name: Comment new comment
      run: echo "$AUTHOR posted the following comment ($URL):\n$BODY"
      env:
        AUTHOR: ${{ github.event.comment.user.login }}
        URL: ${{ github.event.comment.html_url }}
        BODY: ${{ github.event.comment.body }}

  info:
    name: print payload
    runs-on: ubuntu-latest
    steps:
    - name: Payload
      uses: hmarr/debug-action@v2
