name: Telegram bot
on: [pull_request, issue_comment]

jobs:
  comment:
    name: Make comment to a chat
    if: github.event_name == "pull_request"
    runs-on: ubuntu-latest

    steps:
    - name: Comment new PR
      run: echo A PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}

    - name: Comment new comment
      if: |
        github.event_name == "issue_comment" &&
        github.event.issue.pull_request
      run: echo A comment on PR $NUMBER
      env:
        NUMBER: ${{ github.event.issue.number }}
